name: Build/release

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
      
# env:
#   DEBUG: '*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm ci